version: 2

shared: &shared
  steps:
    - checkout
    - run:
        name: install dependencies
        command: |
          make dev
    - run:
        name: Run Tests
        command: |
          make test
    - store_artifacts:
        path: htmlcov/

jobs:
  py39:
    <<: *shared
    docker:
      - image: circleci/python:3.9

  py38:
    <<: *shared
    docker:
      - image: circleci/python:3.8

  py37:
    <<: *shared
    docker:
      - image: circleci/python:3.7

  Deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: install python dependencies
          command: |
            make dev
            make deploy
      - run:
          name: create packages
          command: |
            make package
      - run:
          name: upload to pypi
          command: |
            twine upload dist/*

workflows:
  version: 2
  BuildAndTest:
    jobs:
      - py39
      - py38
      - py37
      - Deploy:
          context:
            - pypi
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
