version: 2.1
jobs:
  BuildAndTest:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            pip install -U pip
            pip install tox && tox
      - store_artifacts:
          path: htmlcov/
      - save_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"
  Deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
      - run:
          name: install python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make dev
      - run:
          name: create packages
          command: |
            make package
      - save_cache:
          key: v1-dependency-cache-{{ checksum "securegroups/__init__.py" }}-{{ checksum "Makefile" }}
          paths:
            - "venv"
            - ".tox"
      - run:
          name: upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2
  SecureGroups:
    jobs:
      - BuildAndTest
      - Deploy:
          context:
            - pypi
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
