# Generated by Django 3.1.1 on 2021-01-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartgroup',
            name='description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
