# Generated by Django 3.1.1 on 2021-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0002_auto_20210103_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartfilter',
            name='grace_period',
            field=models.IntegerField(default=5),
        ),
    ]
