# Generated by Django 3.1.1 on 2021-01-05 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('securegroups', '0005_auto_20210104_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInGroupFilter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
            ],
            options={
                'verbose_name': 'Smart Filter: User Has Group',
                'verbose_name_plural': 'Smart Filter: User Has Group',
            },
        ),
    ]
