# Generated by Django 3.1.1 on 2021-01-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0006_useringroupfilter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartfilter',
            options={'verbose_name': 'Smart Filter Binding',
                     'verbose_name_plural': 'Smart Filter Catalog'},
        ),
    ]
