# Generated by Django 3.1.1 on 2021-01-17 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0007_auto_20210105_0735'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='altalliancefilter',
            options={'verbose_name': 'Smart Filter: Character in Alliance',
                     'verbose_name_plural': 'Smart Filter: Character in Alliance'},
        ),
        migrations.AlterModelOptions(
            name='altcorpfilter',
            options={'verbose_name': 'Smart Filter: Character in Corporation',
                     'verbose_name_plural': 'Smart Filter: Character in Corporation'},
        ),
    ]
