# Generated by Django 3.1.2 on 2021-01-07 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_fleetup_permission'),
        ('securegroups', '0008_auto_20210117_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInStateFilter',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('state', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='authentication.state')),
            ],
            options={
                'verbose_name': 'Smart Filter: User Has State',
                'verbose_name_plural': 'Smart Filter: User Has State',
            },
        ),
    ]
