# Generated by Django 3.1.1 on 2021-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eveonline', '0012_index_additions'),
        ('securegroups', '0008_auto_20210117_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='altalliancefilter',
            name='exempt_alliances',
            field=models.ManyToManyField(
                blank=True, related_name='alli_exempt_alliances', to='eveonline.EveAllianceInfo'),
        ),
        migrations.AddField(
            model_name='altalliancefilter',
            name='exempt_corporations',
            field=models.ManyToManyField(
                blank=True, related_name='alli_exempt_corporations', to='eveonline.EveCorporationInfo'),
        ),
        migrations.AddField(
            model_name='altcorpfilter',
            name='exempt_alliances',
            field=models.ManyToManyField(
                blank=True, related_name='corp_exempt_alliances', to='eveonline.EveAllianceInfo'),
        ),
        migrations.AddField(
            model_name='altcorpfilter',
            name='exempt_corporations',
            field=models.ManyToManyField(
                blank=True, related_name='corp_exempt_corporations', to='eveonline.EveCorporationInfo'),
        ),
        migrations.AddField(
            model_name='useringroupfilter',
            name='exempt_alliances',
            field=models.ManyToManyField(
                blank=True, related_name='group_exempt_alliances', to='eveonline.EveAllianceInfo'),
        ),
        migrations.AddField(
            model_name='useringroupfilter',
            name='exempt_corporations',
            field=models.ManyToManyField(
                blank=True, related_name='group_exempt_corporations', to='eveonline.EveCorporationInfo'),
        ),
    ]
