# Generated by Django 3.1.1 on 2021-06-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0009_auto_20210218_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartgroup',
            options={'permissions': (('access_sec_group', 'Can access sec group requests screen.'), (
                'audit_sec_group', 'Can audit sec groups members.'))},
        ),
    ]
