# Generated by Django 4.0.8 on 2023-03-31 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('securegroups', '0010_perms_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartgroup',
            name='notify_on_add',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='smartgroup',
            name='notify_on_grace',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='smartgroup',
            name='notify_on_remove',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PendingNotification',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('removal', models.BooleanField(default=False)),
                ('notified', models.BooleanField(default=True)),
                ('filter', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='securegroups.smartfilter')),
                ('group', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='securegroups.smartgroup')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
