# Generated by Django 4.0.8 on 2023-03-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0011_smartgroup_notify_on_add_smartgroup_notify_on_grace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingnotification',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
