# Generated by Django 4.0.10 on 2023-04-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0012_alter_pendingnotification_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='useringroupfilter',
            name='reversed_logic',
            field=models.BooleanField(default=False),
        ),
    ]
