# Generated by Django 4.0.10 on 2023-11-20 08:02

from django.db import migrations


def migrate_group_to_groups(apps, schema_editor):
    UserInGroupFilter = apps.get_model('securegroups', 'UserInGroupFilter')

    for gFilter in UserInGroupFilter.objects.all():
        # Take the group and add it to the many to many.
        gFilter.groups.add(gFilter.group)


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0014_useringroupfilter_groups'),
    ]

    operations = [
        migrations.RunPython(migrate_group_to_groups)
    ]
