# Generated by Django 4.0.10 on 2023-11-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0015_migrate_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useringroupfilter',
            name='group',
        ),
    ]
