# Generated by Django 4.2.23 on 2025-11-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0017_filterexpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='altcorpfilter',
            name='main_only',
            field=models.BooleanField(default=False, help_text="Only check the user's main character"),
        ),
    ]
