# Generated by Django 4.2.23 on 2025-06-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securegroups', '0017_filterexpression'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordActivatedFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'verbose_name': 'Smart Filter: Discord',
                'verbose_name_plural': 'Smart Filter: Discord',
            },
        ),
    ]
