# Generated by Django 4.2.16 on 2026-02-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eveonline", "0017_alliance_and_corp_names_are_not_unique"),
        ("securegroups", "0017_filterexpression"),
    ]

    operations = [
        migrations.CreateModel(
            name="AltFactionFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
                (
                    "alt_faction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveonline.evefactioninfo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Smart Filter: Character in Faction",
                "verbose_name_plural": "Smart Filter: Character in Faction",
            },
        ),
    ]
