# Generated by Django 5.2.12 on 2026-05-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securegroups", "0019_smartgroup_last_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartgroup",
            name="last_scheduled",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
