# Generated by Django 5.2.12 on 2026-05-31 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securegroups", "0020_smartgroup_last_scheduled"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartgroup",
            name="last_run_timing",
            field=models.TextField(blank=True, default="", editable=False),
        ),
    ]
