# Generated by Django 5.2.12 on 2026-06-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("securegroups", "0021_smartgroup_last_run_timing"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has Discord",
                "verbose_name_plural": "Smart Filter: User Has Discord",
            },
        ),
        migrations.CreateModel(
            name="DiscourseActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has Discourse",
                "verbose_name_plural": "Smart Filter: User Has Discourse",
            },
        ),
        migrations.CreateModel(
            name="Ips4ActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has IPS4",
                "verbose_name_plural": "Smart Filter: User Has IPS4",
            },
        ),
        migrations.CreateModel(
            name="MumbleActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has Mumble",
                "verbose_name_plural": "Smart Filter: User Has Mumble",
            },
        ),
        migrations.CreateModel(
            name="OpenfireActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has Openfire",
                "verbose_name_plural": "Smart Filter: User Has Openfire",
            },
        ),
        migrations.CreateModel(
            name="Phpbb3ActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has phpBB3",
                "verbose_name_plural": "Smart Filter: User Has phpBB3",
            },
        ),
        migrations.CreateModel(
            name="SmfActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has SMF",
                "verbose_name_plural": "Smart Filter: User Has SMF",
            },
        ),
        migrations.CreateModel(
            name="Teamspeak3ActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has TeamSpeak3",
                "verbose_name_plural": "Smart Filter: User Has TeamSpeak3",
            },
        ),
        migrations.CreateModel(
            name="XenforoActiveFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("description", models.CharField(max_length=500)),
            ],
            options={
                "verbose_name": "Smart Filter: User Has XenForo",
                "verbose_name_plural": "Smart Filter: User Has XenForo",
            },
        ),
    ]
